spring:
  profiles:
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/pointdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password: password

  jpa:
    show-sql: on
    properties:
      hibernate.format_sql: true
      hibernate.highlight_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.jdbc: trace

server:
  port: 8080